CC=gcc
CFLAGS=-Wall -Wextra -Werror -O3

.PHONY: all clean

all: lab11hvdN32491
clean:
	@rm -rf *.o lab11hvdN32491
lab11hvdN32491: lab11hvdN32491.c
	$(CC) $(CFLAGS) -o lab11hvdN32491 lab11hvdN32491.c
